title: era2010-coder's blog
author: era2010-coder
email: your-email@domain.com
description: > 
era2010-coder's blog

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
