title: snowcatridge10's blog
author: snowcatridge10
email: your-email@domain.com
description: > 
description: > # this means to ignore newlines until "baseurl:"
  snowcatridge10's blog

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
